---
- name: Set User
  hosts: dev
  gather_facts: false
  become: false

  tasks:
  - name: Run PowerShell Script
    win_command: hostname.exe
  - name: Run dir 
    ansible.windows.win_command:
      cmd: dir
