---
- name: Set User
  hosts: dev
  gather_facts: false
  become: false

  tasks:
  - delegate_to: localhost
    command: ls -lia
  - name: Run PowerShell Script
    win_command: hostname.exe
  - name: Run a command under a non-Powershell interpreter (cmd in this case)
    ansible.windows.win_shell: |
      dir
      echo %cd%
    args:
      executable: cmd

