name: C++ Build and Version Bump

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      # Paths for which we are never going to be creating releases.
      - ".devcontainer/**"
      - ".github/**"
      - ".git**"
      - "**.md"

jobs:
  login:
    runs-on: ubuntu-latest
    outputs:
      docker_pass: ${{ steps.retrieve_ecr_creds.outputs.docker_pass }}
    steps:
      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1
      - name: Retrive ECR creds
        id: retrieve_ecr_creds
        run: |
          export DOCKER_PASS=$(aws ecr get-login-password --region us-east-1)
          echo "docker_pass=$DOCKER_PASS" >> "$GITHUB_OUTPUT" 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
  test:
    needs: login
    runs-on: windows-2016
    #container:
    #  image: 455322276374.dkr.ecr.us-east-1.amazonaws.com/vs_2010_env:v1
    #  credentials:
    #    username: AWS
    #    password: ${{needs.login.outputs.docker_pass}}
    steps:
      - name: Docker login
        run: docker login --username AWS -p ${{needs.login.outputs.docker_pass}} 455322276374.dkr.ecr.us-east-1.amazonaws.com
      - name: Docker run
        shell: pwsh
        run: |
          (docker manifest inspect 455322276374.dkr.ecr.us-east-1.amazonaws.com/vs_2010_env:v1 -v | ConvertFrom-Json).Descriptor.platform."os.version"
          docker run -dit 455322276374.dkr.ecr.us-east-1.amazonaws.com/vs_2010_env:v1 powershell.exe -Command hostname
        
  
