name: C++ Build and Version Bump

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      # Paths for which we are never going to be creating releases.
      - ".devcontainer/**"
      - ".github/**"
      - ".git**"
      - "**.md"

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1
      - name: retrieve_ecr_creds
        run: |
          export DOCKER_PASS=$(aws ecr get-login-password --region us-east-1)
          echo "::set-output name=docker_pass::${DOCKER_PASS}"
          echo $DOCKER_PASS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
    outputs:
      docker_pass: ${{ steps.retrieve_ecr_creds.outputs.docker_pass }}
  test:
    needs: login
    runs-on: ubuntu-latest
    container:
      image: 455322276374.dkr.ecr.us-east-1.amazonaws.com/vs_2010_env:v1
      credentials:
        username: AWS
        password: ${{ needs.login.outputs.docker_pass }}
    steps:
      - run: echo "Inside a container pulled from ECR \o/"
  
